# Development Environment Configuration

# Service Configuration
service:
  name: tradeshowscout-ocr
  host: 0.0.0.0
  port: 8000
  debug: true
  environment: development

# OCR Configuration
ocr:
  tesseract_path: /usr/local/bin/tesseract
  min_confidence: 0.8
  max_retries: 3
  timeout: 300
  batch_size: 10
  language: eng

# Database Configuration
database:
  url: postgresql://localhost:5432/tradeshowscout_dev
  pool_size: 5
  max_overflow: 10
  echo: true

# Redis Configuration
redis:
  url: redis://localhost:6379/0
  max_memory: 2gb
  max_memory_policy: allkeys-lru

# Storage Configuration
storage:
  upload_path: data/uploads
  processed_path: data/processed
  max_file_size: 10485760  # 10MB
  allowed_extensions:
    - .jpg
    - .jpeg
    - .png
    - .pdf

# Queue Configuration
queue:
  worker_count: 4
  task_timeout: 600
  max_retries: 3
  retry_delay: 300

# Monitoring
monitoring:
  prometheus_port: 9090
  metrics_path: /metrics
  collection_interval: 15

# Logging
logging:
  level: DEBUG
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: logs/ocr-service.log
  max_size: 10485760  # 10MB
  backup_count: 5